services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "80"
      - "5432:5432"
    networks:
      - api-vendas-2024
    volumes:
      - postgres_data:/postgresql

  api-rest:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3333:3333"
    networks:
      - api-vendas-2024
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  api-vendas-2024:

