services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    networks:
      - api-vendas-2024
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    networks:
      - api-vendas-2024
    depends_on:
      - postgres
    volumes:
      - ./:/var/www
    command: 'sh -c ./start.sh'

volumes:
  postgres_data:
    driver: local

networks:
  api-vendas-2024:
